version: 2
jobs:
  build:
    docker:
      - image: ruby:2.5.1
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: RAILS_ENV=test bundle exec rails db:test:prepare
      - run: bundle exec rspec -fdoc
